// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RailwaySections.Persistence;

#nullable disable

namespace RailwaySections.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RailwaySections.Domain.RailwaySections.RailwaySection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.ComplexProperty<Dictionary<string, object>>("Parameters", "RailwaySections.Domain.RailwaySections.RailwaySection.Parameters#RailwaySectionParameters", b1 =>
                        {
                            b1.Property<string>("RailwayCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("parameters_railway_code");

                            b1.Property<string>("UnifiedNetworkMarking")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("parameters_unified_network_marking");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "RailwaySections.Domain.RailwaySections.RailwaySection.Title#RailwaySectionTitle", b1 =>
                        {
                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("title_full_name");

                            b1.Property<string>("Mnemonic")
                                .HasColumnType("text")
                                .HasColumnName("title_mnemonic");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("title_name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_railway_sections");

                    b.ToTable("railway_sections", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
