// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trains.Persistence;

#nullable disable

namespace Trains.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250511220521_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trains.Domain.Trains.Train", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.ComplexProperty<Dictionary<string, object>>("ExternalIdentifier", "Trains.Domain.Trains.Train.ExternalIdentifier#ExternalIdentifier", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_identifier_value");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Parameters", "Trains.Domain.Trains.Train.Parameters#TrainParameters", b1 =>
                        {
                            b1.Property<int>("GrossWeight")
                                .HasColumnType("integer")
                                .HasColumnName("parameters_gross_weight");

                            b1.Property<int>("Length")
                                .HasColumnType("integer")
                                .HasColumnName("parameters_length");

                            b1.Property<int>("NetWeight")
                                .HasColumnType("integer")
                                .HasColumnName("parameters_net_weight");

                            b1.Property<int>("NumberOfWagons")
                                .HasColumnType("integer")
                                .HasColumnName("parameters_number_of_wagons");
                        });

                    b.HasKey("Id")
                        .HasName("pk_trains");

                    b.ToTable("trains", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
